name: Scala CI

on:
  push:
    branches: [ master ]

jobs:
  build_scala:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout source"
      uses: actions/checkout@v2
    - name: "Set up JDK 1.8"
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: pwd
      run: pwd
    - name: "where is the code"
      run: echo $GITHUB_WORKSPACE
    - name: ls
      run: ls -la $GITHUB_WORKSPACE

    - name: "list sbt projects"
      run: cd "$GITHUB_WORKSPACE/core" && sbt projects
    - name: "load dependencies"
      run: cd "$GITHUB_WORKSPACE/core" && sbt reload
    - name: "run domain tests"
      run: cd "$GITHUB_WORKSPACE/core" && sbt "project core" test
      env:
        SBT_OPTS: "-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M -Duser.timezone=GMT"
    - name: "build domain.js artifact"
      run: cd "$GITHUB_WORKSPACE/core" && sbt fullOptJS
      env:
        SBT_OPTS: "-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M -Duser.timezone=GMT"
    - name: "check domain.js artifact"
      run: ls -la "$GITHUB_WORKSPACE/core/optic/js/target/scala-2.12/optic-core-opt.js"
    - name: "name domain.js artifact"
      run: cp "$GITHUB_WORKSPACE/core/optic/js/target/scala-2.12/optic-core-opt.js" "$GITHUB_WORKSPACE/core/optic/js/target/scala-2.12/domain.js"
    - name: "save domain.js artifact"
      uses: actions/upload-artifact@v2
      with:
        name: domain-js
        path: "core/optic/js/target/scala-2.12/domain.js"
        
    
    - name: "build avro artifact"
      run: cd "$GITHUB_WORKSPACE/core" && sbt "opticJVM/runMain com.useoptic.types.AvroMappings"
      
    - name: "build typescript artifact"
      run: cd "$GITHUB_WORKSPACE/core" && sbt "opticJVM/generateTypescript"
    
    - name: "save avro and typescript artifacts"
      uses: actions/upload-artifact@v2
      with:
        name: domain-avro-ts
        path: "core/build"

  build_js:
    runs-on: ubuntu-latest
    needs: build_scala
    steps:
    - name: "checkout source"
      uses: actions/checkout@v2
    - name: pwd
      run: pwd
    - name: "where is the code"
      run: echo $GITHUB_WORKSPACE
    - name: ls
      run: ls -la $GITHUB_WORKSPACE
    - name: "download domain.js artifact"
      uses: actions/download-artifact@v2
      with:
        name: domain-js
        path: "workspace/packages/domain/src"
          
    - name: "check domain src directory"
      run: ls -laR "$GITHUB_WORKSPACE/workspace/packages/domain/src"

    - name: "download avro and typescript artifacts"
      uses: actions/download-artifact@v2
      with:
        name: domain-avro-ts
        path: "workspace/packages/domain-types/src"
        
    - name: "check domain-types src directory"
      run: ls -laR "$GITHUB_WORKSPACE/workspace/packages/domain-types/src"
      
    - name: "set up node.js"
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: "install dependencies"
      run: cd "$GITHUB_WORKSPACE/workspace" && yarn install
    - name: "build workspaces"
      run: cd "$GITHUB_WORKSPACE/workspace" && yarn wsrun --stages --report --fast-exit ws:build

    - name: "check domain build directory"
      run: ls -laR "$GITHUB_WORKSPACE/workspace/packages/domain/build"
    - name: "check domain-types build directory"
      run: ls -laR "$GITHUB_WORKSPACE/workspace/packages/domain-types/build"

    - name: "prepare to publish to npm"
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.PUBLISH_NPM_OPTIC_BOT }}" > ~/.npmrc
    - run: cd "$GITHUB_WORKSPACE/workspace/packages/domain-types" && npm publish --access public
    - run: cd "$GITHUB_WORKSPACE/workspace/packages/domain" && npm publish --access public
    - run: cd "$GITHUB_WORKSPACE/workspace/packages/domain-utilities" && npm publish --access public

