name: Domain Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_scala:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout source"
      uses: actions/checkout@v2
    - name: "Set up JDK 1.8"
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: pwd
      run: pwd
    - name: "where is the code"
      run: echo $GITHUB_WORKSPACE
    - name: ls
      run: ls -la $GITHUB_WORKSPACE

    - name: "list sbt projects"
      run: cd "$GITHUB_WORKSPACE/core" && sbt projects
    - name: "load dependencies"
      run: cd "$GITHUB_WORKSPACE/core" && sbt reload
    - name: "run domain tests"
      run: cd "$GITHUB_WORKSPACE/core" && sbt "project core" test
      env:
        SBT_OPTS: "-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M -Duser.timezone=GMT"
